version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shortener
    ports:
      - '5532:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    container_name: redis_cache
    restart: always
    ports:
      - '6579:6379'

  backend:
    build: ./backend
    container_name: url_shortener_backend
    restart: always
    depends_on:
      - postgres
      - redis
    ports:
      - '3000:3000'
    environment:
      - ENVIRONMENT=development
      - DATABASE_URL=postgresql://user:password@postgres:5432/shortener
      - REDIS_URL=redis://redis:6379
      - BASE_URL=http://localhost:3000
      - JWT_SECRET=Fejai@*123JDa2

  frontend:
    build: ./frontend
    container_name: url_shortener_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - '5173:5173'

volumes:
  postgres_data:
